description: "Updated UnDraw library. These illustrations are designed by Katerina Limpitsouni."
name: "ms_undraw"
repository: "https://github.com/Marcus-Software/ms_undraw"
version: "3.2.0+4"
dependencies:
  flutter_svg: ^2.0.7
  http: ^1.1.0
  flutter:
    sdk: "flutter"
dev_dependencies:
  cli_util: ^0.4.0
  yaml: ^3.1.1
  fhir_yaml: ^0.9.0
  flutter_test:
    sdk: "flutter"
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter: null
